apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: dag-diamond-
spec:
  entrypoint: diamond
  templates:
  - name: echo
    inputs:
      parameters:
      - name: message
    container:
      image: alpine:3.7
      command: [echo, "{{inputs.parameters.message}}"]
  - name: diamond
    dag:
      tasks:
      - name: A
        template: echo
        arguments:
          parameters: [{name: message, value: A}]
      - name: B
        dependencies: [A]
        template: echo
        arguments:
          parameters: [{name: message, value: B}]
      - name: C
        dependencies: [A]
        template: echo
        arguments:
          parameters: [{name: message, value: C}]
      - name: D
        dependencies: [B, C]
        template: echo
        arguments:
          parameters: [{name: message, value: D}]

# As an alternative to specifying sequences of steps, you can define a workflow 
# as a directed-acyclic graph (DAG) by specifying the dependencies of each task. 
# DAGs can be simpler to maintain for complex workflows and allow for maximum 
# parallelism when running tasks.

# In the above workflow, step A runs first, as it has no dependencies. Once A 
# has finished, steps B and C run in parallel. Finally, once B and C have completed, 
# step D runs.